version: '2'
services:
  db:
    image: mysql:latest
    ports:
      - "6606:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root2018
      MYSQL_DATABASE: CLEO
    volumes:
      - ./mysql.conf.d:/etc/mysql/conf.d
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
